import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import I18nProvider from "@/context/i18n-provider";
import AuthProvider from "@/components/common/AuthProvider";
import { ThemeProvider } from '@/context/ThemeContext';
import { WebVitals } from "@/components/common/WebVitals";
import ReactQueryProvider from "@/components/common/ReactQueryProvider";
import NotificationToaster from "@/components/notifications/NotificationToaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Diệu Diệu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <WebVitals/>
        <NotificationToaster/>
        <I18nProvider>
          <ThemeProvider>
            <AuthProvider>
              <ReactQueryProvider>
                {children}
              </ReactQueryProvider>
            </AuthProvider>
          </ThemeProvider>
        </I18nProvider>
        
      </body>
    </html>
  );
}
